### ISSUE TITLE
`Projections` are quantities, but they spawn odd offspring

### ISSUE THREAD

**Issue by keflavich** [radio-astro-tools/spectral-cube#123]
If you create a projection, then multiply it, then try to access a `projection` property, you get an error:

```
>>> blah = cube.sum(axis=0) * 5
>>> blah.hdu
Traceback (most recent call last):
  File "<ipython-input-9-a55e6f49c03a>", line 1, in <module>
    blah.hdu
  File "/Users/adam/repos/astropy/astropy/units/quantity.py", line 667, in __getattr__
    attr))
AttributeError: 'Projection' object has no 'hdu' member

> /Users/adam/repos/astropy/astropy/units/quantity.py(667)__getattr__()
    666                     self.__class__.__name__,
--> 667                     attr))
    668
```

but `blah` is still a projection:
```
>>> type(blah)
spectral_cube.spectral_cube.Projection
```

I think we need to do something more in `Projection` - maybe define `__new__`? - to get this to work properly.

cc @astrofrog

**Comment by e-koch** [comment]
Addressed in #265
