### ISSUE TITLE
Add dask parallelization routines

### ISSUE THREAD

**Issue by keflavich** [radio-astro-tools/spectral-cube#566]
The parallelization I wrote using joblib is... sub-optimal.  I've had it frequently result in tracebacks like this:

```
/lustre/naasc/users/aginsbur/anaconda/lib/python3.6/site-packages/radio_beam-0.3.1-py3.6.egg/radio_beam/multiple_beams.py:258: UserWarning: Do not use the average beam for convolution! Use the smallest common beam from `Beams.common_beam()`.
  warnings.warn("Do not use the average beam for convolution! Use the"
WARNING: BeamAverageWarning: Arithmetic beam averaging is being performed.  This is not a mathematically robust operation, but is being permitted because the beams differ by <1 [spectral_cube.base_class]
---------------------------------------------------------------------------
_RemoteTraceback                          Traceback (most recent call last)
_RemoteTraceback: 
'''
Traceback (most recent call last):
  File "/lustre/naasc/users/aginsbur/anaconda/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 391, in _process_worker
    call_item = call_queue.get(block=True, timeout=timeout)
  File "/lustre/naasc/users/aginsbur/anaconda/lib/python3.6/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/lustre/naasc/users/aginsbur/anaconda/lib/python3.6/site-packages/joblib/_memmapping_reducer.py", line 196, in _strided_from_memmap
    offset=offset, order=order)
  File "/lustre/naasc/users/aginsbur/anaconda/lib/python3.6/site-packages/joblib/backports.py", line 23, in make_memmap
    shape=shape, order=order)
  File "/lustre/naasc/users/aginsbur/anaconda/lib/python3.6/site-packages/numpy/core/memmap.py", line 225, in __new__
    f_ctx = open(os_fspath(filename), ('r' if mode == 'c' else mode)+'b')
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp_7j7aarc'
'''

The above exception was the direct cause of the following exception:

BrokenProcessPool                         Traceback (most recent call last)
<ipython-input-8-b4f7405e0d9d> in <module>
----> 1 sigmaclipcube = cube.sigma_clip(1.8, num_cores=8, use_memmap=True, parallel=True)

/lustre/naasc/users/aginsbur/repos/spectral-cube/spectral_cube/spectral_cube.py in sigma_clip(self, threshold, verbose, use_memmap, num_cores, **kwargs)
   2911                                                      use_memmap=use_memmap,
   2912                                                      verbose=verbose,
-> 2913                                                      **kwargs)
   2914 
   2915     def spectral_smooth(self, kernel,

/lustre/naasc/users/aginsbur/repos/spectral-cube/spectral_cube/base_class.py in newfunc(*args, **kwargs)
    628                 avg_beam = self.average_beams(beam_threshold, warn=True)
    629 
--> 630             result = function(*args, **kwargs)
    631 
    632             if not isinstance(result, LowerDimensionalObject):

/lustre/naasc/users/aginsbur/repos/spectral-cube/spectral_cube/spectral_cube.py in apply_function_parallel_spectral(self, function, num_cores, verbose, use_memmap, parallel, **kwargs)
   2882                                                   verbose=verbose,
   2883                                                   num_cores=num_cores,
-> 2884                                                   **kwargs
   2885                                                  )
   2886 

/lustre/naasc/users/aginsbur/repos/spectral-cube/spectral_cube/spectral_cube.py in _apply_function_parallel_base(self, iteration_data, function, applicator, num_cores, verbose, use_memmap, parallel, memmap_dir, update_function, **kwargs)
   2743                                                               function,
   2744                                                               **kwargs)
-> 2745                                           for arg in iteration_data)
   2746             except ImportError:
   2747                 if num_cores is not None and num_cores > 1:

/lustre/naasc/users/aginsbur/anaconda/lib/python3.6/site-packages/joblib/parallel.py in __call__(self, iterable)
    932 
    933             with self._backend.retrieval_context():
--> 934                 self.retrieve()
    935             # Make sure that we get a last message telling us we are done
    936             elapsed_time = time.time() - self._start_time

/lustre/naasc/users/aginsbur/anaconda/lib/python3.6/site-packages/joblib/parallel.py in retrieve(self)
    831             try:
    832                 if getattr(self._backend, 'supports_timeout', False):
--> 833                     self._output.extend(job.get(timeout=self.timeout))
    834                 else:
    835                     self._output.extend(job.get())

/lustre/naasc/users/aginsbur/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py in wrap_future_result(future, timeout)
    519         AsyncResults.get from multiprocessing."""
    520         try:
--> 521             return future.result(timeout=timeout)
    522         except LokyTimeoutError:
    523             raise TimeoutError()

/lustre/naasc/users/aginsbur/anaconda/lib/python3.6/concurrent/futures/_base.py in result(self, timeout)
    430                 raise CancelledError()
    431             elif self._state == FINISHED:
--> 432                 return self.__get_result()
    433             else:
    434                 raise TimeoutError()

/lustre/naasc/users/aginsbur/anaconda/lib/python3.6/concurrent/futures/_base.py in __get_result(self)
    382     def __get_result(self):
    383         if self._exception:
--> 384             raise self._exception
    385         else:
    386             return self._result

BrokenProcessPool: A task has failed to un-serialize. Please ensure that the arguments of the function are all picklable.
```

So, we should try using dask under the hood.  In principle, it should work just fine.  I don't yet know how to go about doing it.  Options include:

 1. The simple and stupid way: 
```
import dask.array
da = dask.array.from_array(cube.filled_data[:], chunks=(200,5,5))
```
This way is probably bad, since it is calling `_get_filled_data` and loading the whole cube into memory, violating all the rules we've established for data handling (on which note... maybe we should write out these rules somewhere...)
2. Some sort of "delayed" way.
```
da = dask.array.from_delayed(cube._get_filled_data, dtype=cube._data._dtype, shape=cube.shape)
```
Does that... maybe just work?  probably not....
3. Or maybe we can do
```
da = dask.array.from_array(cube.filled_data, chunks=(200,5,5))
```
but to make this work, we need the `SliceIndexer` class to have a `shape` and `dtype` attribute (it already has `__getitem__`)

**Comment by keflavich** [comment]
Closed because we use dask now
