### ISSUE TITLE
CASA reader slicing failure

### ISSUE THREAD

**Issue by keflavich** [radio-astro-tools/spectral-cube#619]
We don't have any means to handle the case `cube.mask is None` when slicing, apparently:

```
In [1]: from spectral_cube import SpectralCube 
   ...: cube = SpectralCube.read('BrickMaser_95_spw25.residual',       format='casa_image') 
   ...: cube[8000,:,:].quicklook() 
   ...:                                                                                                                                                        


Traceback (most recent call last):
  File "<ipython-input-1-a6ff7026aa7e>", line 3, in <module>
    cube[8000,:,:].quicklook()
  File "/orange/adamginsburg/repos/spectral-cube/spectral_cube/spectral_cube.py", line 1242, in __getitem__
    mask=self.mask[view],
TypeError: 'NoneType' object is not subscriptable
```

**Comment by keflavich** [comment]
re: https://github.com/radio-astro-tools/spectral-cube/pull/618#issuecomment-604593758 - probably this residual cube does not have a mask; it wasn't even done writing at the time I read it
