### ISSUE TITLE
CASA read performance

### ISSUE THREAD

**Issue by keflavich** [radio-astro-tools/spectral-cube#675]
I'm testing on some 45 GB 2k x 2k x 2k ish cubes, and the chunk size is affecting CASA cube read times dramatically.  We cannot rely on default chunk sizes; dask does not choose them for us in a reasonable way.

Two competing examples:
```
In [31]: cuberc._data
Out[31]: dask.array<rechunk-merge, shape=(2114, 2450, 2450), dtype=float32, chunksize=(168, 420, 420), chunktype=numpy.ndarray>

In [32]: cube.write('W43-MM2_B3_spw0_12M_spw0.image.fits')
[                                        ] | 0% Completed | 13min  3.8s
```

vs

```

In [17]: cube
Out[17]:
DaskVaryingResolutionSpectralCube with shape=(1944, 2450, 2450) and unit=Jy / beam and chunk size (10, 2450, 2450):
 n_x:   2450  type_x: RA---SIN  unit_x: deg    range:   281.868520 deg:  281.936591 deg
 n_y:   2450  type_y: DEC--SIN  unit_y: deg    range:    -2.048222 deg:   -1.980194 deg
 n_s:   1944  type_s: FREQ      unit_s: Hz     range: 91701673059.627 Hz:92650390515.531 Hz

In [18]: cube.write('W43-MM2_B3_spw1_12M_spw1.image.fits')
[########                                ] | 21% Completed | 10min 25.6s
```

I'm also testing against casa's exportfits, but it looks like we could default to a FITS-like chunking instead of leaving the default untouched.

**Comment by keflavich** [comment]
export fits is many times faster:
```

In [5]: !du -h W43-MM2_B3_spw2_12M_spw2.image
116K    W43-MM2_B3_spw2_12M_spw2.image/logtable
1.2G    W43-MM2_B3_spw2_12M_spw2.image/mask0
37G     W43-MM2_B3_spw2_12M_spw2.image

In [6]: t0 = time.time(); print(t0); exportfits('W43-MM2_B3_spw2_12M_spw2.image', 'W43-MM2_B3_spw2_12M_spw2.image.fits'); print(time.time() - t0); print(time.time())
1602962942.8062358
231.00269675254822
1602963173.8103726
```
231s for a 37 GB cube, as opposed to 
```
In [18]: cube.write('W43-MM2_B3_spw1_12M_spw1.image.fits')
[####################                    ] | 50% Completed | 25min 54.4s
```
about 50 minutes (15 times slower) for a flat-chunked cube.

I'm inclined to suggest we remove CASA image support by default unless we can fix this issue.

**Comment by astrofrog** [comment]
What version of astropy are you using?

**Comment by keflavich** [comment]
astropy 4.0.1.post1 (`pip install -e` version), spectral cube also latest dev, thought perhaps from a week ago

**Comment by keflavich** [comment]
performance is just as awful with:
```
In [13]: astropy.__version__
Out[13]: '4.2.dev913+g079fcb73a'

In [14]: spectral_cube.__version__
Out[14]: '0.5.1.dev36+g71fd8e2'
```

**Comment by astrofrog** [comment]
@keflavich performance should be dramatically different between 4.0.1 and 4.1+ - can you try with 4.1rc2 to double check?

**Comment by astrofrog** [comment]
astropy 4.0.x doesn't support dask arrays properly so should have terrible performance

**Comment by keflavich** [comment]
Oh, what changed in 4.1?  

Anyway, my last test was on 4.2.dev, so should that have corrected the issue?  It didn't.

dask version:
```
In [16]: dask.__version__
Out[16]: '2.23.0'
```

**Comment by keflavich** [comment]
hm, not performance, but an actual write failure:
```

In [18]: cube.write('W43-MM2_B3_spw1_12M_spw1.image.fits')                                                                                                                                                |
[########################################] | 100% Completed | 55min 55.5s                                                                                                                                 |
Traceback (most recent call last):                                                                                                                                                                        |
  File "<ipython-input-18-d4df758d7bac>", line 1, in <module>                                                                                                                                             |
    cube.write('W43-MM2_B3_spw1_12M_spw1.image.fits')                                                                                                                                                     |
  File "/orange/adamginsburg/repos/spectral-cube/spectral_cube/dask_spectral_cube.py", line 1368, in write                                                                                                |
    super().write(*args, **kwargs)                                                                                                                                                                        |
  File "/orange/adamginsburg/repos/spectral-cube/spectral_cube/io/core.py", line 131, in __call__                                                                                                         |
    registry.write(self._instance, *args, **kwargs)                                                                                                                                                       |
  File "/orange/adamginsburg/miniconda3/envs/casa6_py36/lib/python3.6/site-packages/astropy/io/registry.py", line 566, in write                                                                           |
  File "/orange/adamginsburg/repos/spectral-cube/spectral_cube/io/fits.py", line 231, in write_fits_cube                                                                                                  |
    hdulist = cube.hdulist                                                                                                                                                                                |
  File "/orange/adamginsburg/repos/spectral-cube/spectral_cube/spectral_cube.py", line 3837, in __getattribute__                                                                                          |
    return super(VRSC, self).__getattribute__(attrname)                                                                                                                                                   |
  File "/orange/adamginsburg/repos/spectral-cube/spectral_cube/dask_spectral_cube.py", line 1381, in hdulist                                                                                              |
    hdu = PrimaryHDU(self._get_filled_data(fill=self._fill_value), header=self.header)                                                                                                                    |
  File "/orange/adamginsburg/miniconda3/envs/casa6_py36/lib/python3.6/site-packages/astropy/io/fits/hdu/image.py", line 993, in __init__                                                                  |
  File "/orange/adamginsburg/miniconda3/envs/casa6_py36/lib/python3.6/site-packages/astropy/io/fits/hdu/image.py", line 142, in __init__                                                                  |
  File "/orange/adamginsburg/miniconda3/envs/casa6_py36/lib/python3.6/site-packages/astropy/utils/decorators.py", line 769, in __set__                                                                    |
  File "/orange/adamginsburg/miniconda3/envs/casa6_py36/lib/python3.6/site-packages/astropy/io/fits/hdu/image.py", line 254, in data                                                                      |
TypeError: data object dask.array<FilledArrayHandler 8733f8ce-601b-4c9c-ac93, shape=(1944, 2450, 2450), dtype=float32, chunksize=(10, 2450, 2450), chunktype=numpy.ndarray> could not be coerced into an n|
darray
```

**Comment by astrofrog** [comment]
https://docs.astropy.org/en/v4.1rc2/whatsnew/4.1.html#whatsnew-4-1-fitsdask

**Comment by astrofrog** [comment]
@keflavich - the line numbers in that traceback suggest you are using astropy 4.0.x

**Comment by keflavich** [comment]
yes, that traceback was with a different version

**Comment by astrofrog** [comment]
@keflavich - I think we should be able to close this - can you check if you still have performance issues with the latest dev version?

**Comment by keflavich** [comment]
I'm running some of the tests that led me here, and I think they're working now.  I haven't done a side-by-side performance test yet, though.

**Comment by keflavich** [comment]
Closing this issue as several changes have improved CASA-related performance.
