### ISSUE TITLE
Apparent incompatibility between dask-mask and BooleanArrayMask?

### ISSUE THREAD

**Issue by keflavich** [radio-astro-tools/spectral-cube#677]
```python
Traceback (most recent call last):
  File "/orange/adamginsburg/ALMA_IMF/reduction/analysis/line_quicklooks.py", line 104, in <module>
    mcube = cube.mask_out_bad_beams(0.1)
  File "/orange/adamginsburg/repos/spectral-cube/spectral_cube/base_class.py", line 736, in mask_out_bad_beams
    newmask = da.logical_and(self._mask_include, includemask)
  File "/orange/adamginsburg/miniconda3/envs/casa6_py36/lib/python3.6/site-packages/dask/array/ufunc.py", line 128, in __call__
    result = dsk._elemwise(self._ufunc, *args, **kwargs)
  File "/orange/adamginsburg/miniconda3/envs/casa6_py36/lib/python3.6/site-packages/dask/array/core.py", line 3932, in elemwise
    for a in args
  File "/orange/adamginsburg/miniconda3/envs/casa6_py36/lib/python3.6/site-packages/dask/array/core.py", line 3932, in <listcomp>
    for a in args
AttributeError: 'BooleanArrayMask' object has no attribute 'ndim'
```

**Comment by keflavich** [comment]
This is built on #639, since #635 triggers an error earlier otherwise.  This might be something to solve within #639

**Comment by keflavich** [comment]
Closing as this may have been solved already.
